### PR TITLE
Add recursion to get and put for local and ssh sessions

### LINKED ISSUE #536: ENH: recursive `get` for sessions (shell, ssh, etc) should support recursive mode of operation
It is necessary for any place where `get` is supposed to obtain a full hierarchy of directories like e.g. getting outputs of the job back to the local system.  

I will send a follow up initial PR for the plain orchestrator to fetch everything not just failed subjobs logs

### PR DESCRIPTION
**Pull request by chaselgrove**
Closes #536

### CODE REVIEW

**Comment by yarikoptic** [comment]
Please add a test

**Comment by chaselgrove** [comment]
This tests a local resource.  How would you test the remote (ssh) transfer?

**Comment by kyleam** [comment]
> How would you test the remote (ssh) transfer?

This PR is about a session method, so I think most of the extensive testing should happen in reproman/resource/tests/test_session.py.  That file already has some tests for `get()`, and I believe one of the cases is against a docker ssh container.

https://github.com/ReproNim/reproman/blob/b82a412ecccce33c885247dbd9464972b0e87c3f/reproman/resource/tests/test_session.py#L303

**Comment by kyleam** [comment]
The [last build](https://travis-ci.org/github/ReproNim/reproman/builds/721440920) had three jobs stall in the test_conda phase.  I tried with and without the changes here to trigger these again on Travis but was unable to.  So perhaps they were just due to connectivity issues.

**Review by kyleam — APPROVED** [review]
Thanks @chaselgrove.  Looks good to me (assuming the tests still pass after my push, which adds a test to cover the recursive part of `transfer_recursive`).

**Comment by yarikoptic** [comment]
Thank you @chaselgrove and @kyleam .  From a brief look at the code -- looks good to me too.

**Pull request merged**
