### PR TITLE
BF+ENHs: a collection of small tune ups/fixes

### PR DESCRIPTION
**Pull request by yarikoptic**
Please review individual commit messages for the descriptions

TODOs:
- ~~fix up singularity testing since there is no `'shub://vsoch/hello-world@42e1f04ed80217895f8c960bdde6bef4d34fab59'` any more~~ singularity will be handled separately (#406)

### CODE REVIEW

**Comment by kyleam** [comment]
>  fix up singularity testing since there is no `'shub://vsoch/hello-world@42e1f04ed80217895f8c960bdde6bef4d34fab59'` any more

There's not?

```
$  singularity pull shub://vsoch/hello-world@42e1f04ed80217895f8c960bdde6bef4d34fab59
Progress |===================================| 100.0% 
Done. Container is at: /tmp/vsoch-hello-world-master-latest.simg
```

**Comment by yarikoptic** [comment]
```shell
$> singularity pull 'shub://vsoch/hello-world@42e1f04ed80217895f8c960bdde6bef4d34fab59'
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   Failed to get manifest from Shub: The requested manifest was not found in singularity hub
```

**Comment by kyleam** [comment]
> Please review individual commit messages for the descriptions

Gladly, but oh how you've changed :]

https://github.com/pyout/pyout/pull/24#issuecomment-355699800

**Comment by yarikoptic** [comment]
> > Please review individual commit messages for the descriptions
> 
> Gladly, but oh how you've changed :]
> 
> [pyout/pyout#24 (comment)](https://github.com/pyout/pyout/pull/24#issuecomment-355699800)

ha ha -- I guess it is all "bad influence"! ;)

**Pull request merged**
