### PR TITLE
Enh/launcher

### PR DESCRIPTION
**Pull request by jbwexler**
I ended up creating a new branch to keep it a bit cleaner. Continuation of https://github.com/ReproNim/reproman/pull/574

### CODE REVIEW

**Comment by jbwexler** [comment]
It looked like pbs was the only other type of submitter that is supported by Launcher at the moment, so I only added launcher compatibility to slurm and pbs. https://github.com/TACC/launcher/tree/master/plugins

**Comment by kyleam** [comment]
Thanks for the update, @jbwexler.  Looks good.  I've pushed a fixup for the test failures and will look into adding a test that uses launcher.

**Comment by kyleam** [comment]
I said:
> and will look into adding a test that uses launcher.

The new tests pass, but codecov flagged some of the new bits in test_orchestrators.py as unexecuted.  Either the tests aren't working as I intended or coverage is confused.  I'll first make sure that the new assertion is being executed locally and then I will push a temporary commit to this PR's branch to check that it's being triggered by the github workflow.

**Comment by kyleam** [comment]
> then I will push a temporary commit to this PR's branch to check that it's being triggered by the github workflow.

The expected lines were triggered.  I'll drop the tip commit and conclude that codecov was/is confused.

https://github.com/ReproNim/reproman/pull/577/checks?check_run_id=2040423024

**Review by kyleam — APPROVED** [review]
Thanks again, @jbwexler.

**Comment by jbwexler** [comment]
No problem, thanks for taking the time to incorporate the PR!

**Pull request merged**
