### PR TITLE
MNT: Avoid invalid escape sequences in strings

### PR DESCRIPTION
**Pull request by kyleam**
A good number of regexps and a few other strings don't use an r-prefix
when the string contains non-escape-sequence backslashes.  This
doesn't make a functional difference at the moment because, when
Python encounters a backslash that produces an invalid escape
sequence, it automatically escapes the backslash.  But Python 3.6 and
later give a DeprecationWarning (<https://bugs.python.org/issue32912>),
with the goal of eventually making invalid escape sequences a syntax
error.

---

~This PR is marked as a draft because it sits on top of gh-571.  Here's the effective diff: https://github.com/repronim/reproman/compare/migrate-to-github-ci...invalid-escapes~

### CODE REVIEW

**Comment by kyleam** [comment]
There are some test failures.  Marking as draft...

**Comment by yarikoptic** [comment]
thank you @kyleam !  I had been fixing for those here and there (in other projects) and totally forgot about the trove of them here ;)

**Comment by yarikoptic** [comment]
probably here (and datalad) we should tune up tests execution so we fail on deprecation warnings and only whitelist the ones out of our control etc.  We do have [such setup e.g. in dandi-cli](https://github.com/dandi/dandi-cli/blob/master/tox.ini#L23) so far for the short term pain and long term gain ;-)

**Comment by kyleam** [comment]
> probably here (and datalad) we should tune up tests execution so we fail on deprecation warnings and only whitelist the ones out of our control etc.

Sounds good.  This PR takes care of the bulk of those that are in our control, but there are still a few remaining ones.

---

The latest push should resolve the test failures.  I think it's correct, but perhaps I'm missing some (untested) detail of the `apt-cache-policy` output.

**Pull request merged**
